### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by SisSim** [Zweistein2/AgrarMonitor#6]
Hi würde gerne den AgrarMonitor benutzen, Aber ich finde die xml nicht. Hast Du die xml entfernt oder bin ich nur zu blöd, die zu finden

**Comment by Zweistein2** [comment]
Welche XML meinst du denn genau?

**Comment by SisSim** [comment]
Oh man, ich bin sogar zu blöd zum Fragen.
Ich meine natürlich die .exe datei

**Comment by Zweistein2** [comment]
Die .exe findest du unter "Releases": https://github.com/Zweistein2/AgrarMonitor/releases/tag/v1.0.1

Dort den Punkt "Assets" ausklappen und die entsprechenden Dateien downloaden

**Comment by SisSim** [comment]
Super, vielen Dank, sieht richtig gut aus

**Comment by Zweistein2** [comment]
Kein Problem, dann mach ich hier zu ;)
